version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - /app/node_modules
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
